### ISSUE TITLE
Fails to register with DBUS if Chromecast name contains spaces

### ISSUE THREAD

**Issue by Elleo** [alexdelorenzo/chromecast_mpris#1]
If a Chromecast's name contains spaces (such as "Living Room TV") chromecast_mpris will terminate with the following exception:

```Traceback (most recent call last):
  File "/home/mike/.local/bin/chromecast_mpris", line 8, in <module>
    sys.exit(cmd())
  File "/home/mike/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mike/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mike/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mike/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mike/.local/lib/python3.8/site-packages/chromecast_mpris/command.py", line 14, in cmd
    main(name, log_level)
  File "/home/mike/.local/lib/python3.8/site-packages/chromecast_mpris/main.py", line 30, in main
    mpris = create_adapters_and_server(name)
  File "/home/mike/.local/lib/python3.8/site-packages/chromecast_mpris/main.py", line 20, in create_adapters_and_server
    mpris.publish()
  File "/home/mike/.local/lib/python3.8/site-packages/mpris_server/server.py", line 48, in publish
    self._publication_token = bus.publish(
  File "/home/mike/.local/lib/python3.8/site-packages/pydbus/publication.py", line 44, in publish
    return Publication(self, bus_name, *objects)
  File "/home/mike/.local/lib/python3.8/site-packages/pydbus/publication.py", line 17, in __init__
    bus_name = auto_bus_name(bus_name)
  File "/home/mike/.local/lib/python3.8/site-packages/pydbus/auto_names.py", line 9, in auto_bus_name
    raise ValueError("invalid bus name")
ValueError: invalid bus name
```

This is because it's attempting to register an invalid DBUS name (e.g. "org.mpris.MediaPlayer2.Living Room TV")

**Comment by alexdelorenzo** [comment]
Good catch! The project's dependency `mpris_server` was updated to validate DBus names, and Chromecast names that are invalid are coerced into valid ones. This issue should be fixed, so I'm going to close it for now. 

Thanks again for filing a bug report.
